spring:
  profiles:
    active: local

server:
  port: 8081

pinpoint:
  modules:
    collector:
      grpc:
        ssl:
          enabled: false
      inspector:
        enabled: false
      metric:
        enabled: false
    realtime:
      enabled: false